from fastapi import HTTPException


class UserAlreadyExistsException(HTTPException): ...


class UserNotExistsException(HTTPException): ...


class UserAlreadyBlockedException(HTTPException): ...


class UserAlreadyActiveException(HTTPException): ...


class BadRequestDataException(HTTPException): ...


class NegativeBalanceException(HTTPException): ...


class TransactionNotExistsException(HTTPException): ...


class TransactionDoesNotBelongToUserException(HTTPException): ...


class TransactionAlreadyRollbackedException(HTTPException): ...
